### ISSUE TITLE
Use the same Layout enum as cblas

### ISSUE THREAD

**Issue by SuperFluffy** [stainless-steel/lapacke#1]
Right now, `cblas::Layout` and `lapacke::Layout` are the technically the same enums int that they have the same representation, but they are still different enums.

Since it's conceivable that `cblas` and `lapacke` might be used in the same context, I think that either `lapacke` should import the enums from `cblas` and reexport them, or alternatively there should be some meta-crate that contains the enum definitions used in both crates.

**Comment by IvanUkhov** [comment]
Thanks for the note! I think this enum is not worth introducing a dependence or a meta crate; the hierarchy is already quite elaborate. If it’s inconvenient to do a proper conversion, one might just transmute; this crate already necessitates the usage of unsafe code.
