### ISSUE TITLE
lapacke may be unsound due to calls to `getenv`

### ISSUE THREAD

**Issue by xerxes12354** [stainless-steel/lapacke#6]
I was looking at the time crate wondering why the [time crate didn't give offsets](https://github.com/time-rs/time/issues/293), and I stumbled upon [this thread on Internals](https://internals.rust-lang.org/t/function-to-hold-lock-on-execution-environment-for-ffi/13702/22). This seems like a big problem so I went looking for FFI crates where this could be a problem.

Looking at lapacke source code it uses some environment variables https://github.com/Reference-LAPACK/lapack/blob/77a0ceb6c9a3c757e7039027f1f324e2811e6ee0/LAPACKE/src/lapacke_nancheck.c#L50, it looks like this wrapper has a data race when `set_env` is called in another thread.

**Comment by IvanUkhov** [comment]
Thank you for the note! This is difficult to handle from here. In general, it is clear that there could be a lot of misuse, which is the reason all functions are labeled unsafe.
